default_platform(:ios)

platform :ios do

  desc "Build and test application"
  lane :test do
    run_tests(scheme: "Halite")
  end

  desc "Push a new build to TestFlight"
  lane :beta do
    increment_build_number(build_number: number_of_commits)
    build_app(scheme: "Halite")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end


  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(build_number: number_of_commits)
    build_app(
      scheme: "Halite",
      export_method: "app-store",
      configuration: "Release",
      include_bitcode: true
    )
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true
    )
  end

end
