default_platform(:ios)

platform :ios do

  desc "Build and test application"
  lane :test do
    run_tests(scheme: "Halite")
  end

  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(
      app_store_build_number + 1,
      xcodeproj: "Halite.xcodeproj"
    )
    build_app(scheme: "Halite")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end

end
